# Generated by Django 5.2.6 on 2025-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0003_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
