# Generated by Django 5.2.6 on 2025-11-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
