# Generated by Django 5.2.6 on 2025-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0008_remove_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='category.category'),
        ),
    ]
