# Generated by Django 5.2.6 on 2025-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
