# Generated by Django 5.2.6 on 2025-11-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_views_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
