# Generated by Django 5.2.6 on 2025-11-06 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_picture_alter_user_username_linkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
