# Generated by Django 5.2.6 on 2025-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_linkuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='static/assets/img/default.jpg', upload_to='account/user_pictures'),
        ),
    ]
