# Generated by Django 5.2.6 on 2025-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SittingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotter_title', models.CharField(max_length=120)),
                ('fotter_description', models.TextField(default='Sign up for free and be the first to get notified about new posts.')),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('telegram_url', models.URLField()),
                ('instagram_url', models.URLField()),
            ],
        ),
    ]
