# Generated by Django 5.2.6 on 2025-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sittingsite',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sittingsite',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sittingsite',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sittingsite',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sittingsite',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
