# Generated by Django 5.2.6 on 2025-11-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sittingsite_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SittingSite',
            new_name='SettingSite',
        ),
    ]
